### ISSUE TITLE
RequestError: self signed certificate

### ISSUE THREAD

**Issue by s-savela** [ptc-iot-sharing/ThingworxDemoWebpackWidget#44]
When running "yarn run upload" I get the following errors:
webpack 5.53.0 compiled successfully in 3159 ms
Failed to delete extension from thingworx because RequestError: self signed certificate.
This is not a critical error
Failed to import extension to thingworx because RequestError: self signed certificate.
This is a critical error

Any guidance on how to fix this?

**Comment by stefan-lacatus** [comment]
It seems like you are trying to upload the extension into an ThingWorx server that uses HTTPS, with a self signed certificate.
This is a normal error, because your local node (that is running the upload script) does not trust the self signed certificate.

There are a couple of ways of going about fixing this:

1. Make node trust this specific certificate by specifying the `NODE_EXTRA_CA_CERTS` environment parameter
2. Make note ignore all SSL errors by setting `NODE_TLS_REJECT_UNAUTHORIZED` to `0`.

I personally almost always go for option 2, because i usually just upload into my local ThingWorx environment.
So, my command will look something like this (in bash, you can search for how to set environment variables for a specific command online): `NODE_TLS_REJECT_UNAUTHORIZED=0 yarn run upload`

See https://levelup.gitconnected.com/how-to-resolve-certificate-errors-in-nodejs-app-involving-ssl-calls-781ce48daded for more information
